"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Compass, ArrowUpRight, ArrowRight, Crosshair, RefreshCw, Plus, Pause } from "lucide-react";
import { projects, type Project } from "@/lib/projects";
import type { Thesis, ThesisCheck, ThesisMetric } from "@/lib/thesis-types";
const date=(value:string)=>new Date(value).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
const labels:Record<ThesisMetric,string>={"transfer-counter":"Transfer counter increases","holder-counter":"Holder-address counter increases","repository-head":"Default-branch head changes","transaction-counter":"Address transaction counter increases"};
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed.");return d;}
function Trajectory({thesis,checks}:{thesis:Thesis;checks:ThesisCheck[]}) {
  if(typeof thesis.baseline.value!=="number")return <p className="report-time">Pinned repository head: {String(thesis.baseline.value).slice(0,12)}. Each check compares against this head.</p>;
  const points=[{at:thesis.baseline.observedAt,value:thesis.baseline.value},...checks.flatMap(c=>c.sample&&typeof c.sample.value==="number"?[{at:c.sample.observedAt,value:c.sample.value}]:[])];
  if(points.length<2)return <div className="thesis-empty-chart">Baseline recorded. The trajectory appears after an evidence check.</div>;
  const baseline=thesis.baseline.value, deltas=points.map(p=>p.value-baseline);
  const min=Math.min(0,...deltas),max=Math.max(thesis.threshold,...deltas),span=Math.max(1,max-min);
  const start=Date.parse(points[0].at), end=Math.max(start+1,Date.parse(points.at(-1)!.at));
  const xy=points.map((p,i)=>({x:24+(Date.parse(p.at)-start)/(end-start)*552,y:130-(deltas[i]-min)/span*104}));
  const thresholdY=130-(thesis.threshold-min)/span*104;
  return <figure className="thesis-chart"><svg viewBox="0 0 600 160" role="img" aria-label={`Observed counter change: ${deltas.at(-1)}. Chosen threshold: ${thesis.threshold}. Line joins sampled observations, not continuous activity.`}><line x1="24" y1={thresholdY} x2="576" y2={thresholdY} stroke="#8da1bd" strokeDasharray="4 5"/><polyline fill="none" stroke="#326bff" strokeWidth="2.5" points={xy.map(p=>`${p.x},${p.y}`).join(" ")}/>{xy.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="4" fill="#326bff"/>)}<text x="24" y="154" fill="#627998" fontSize="11">{date(points[0].at)}</text><text x="576" y="154" textAnchor="end" fill="#627998" fontSize="11">{date(points.at(-1)!.at)}</text></svg><figcaption>Observed change {deltas.at(-1)!>=0?"+":""}{deltas.at(-1)} · chosen threshold +{thesis.threshold}. Lines connect samples; gaps are not measured activity.</figcaption></figure>;
}
export function ThesisDesk({initialProject="sun-token"}:{initialProject?:string}) {
  const [catalog,setCatalog]=useState<Project[]>(projects),[theses,setTheses]=useState<Thesis[]>([]),[selected,setSelected]=useState<Thesis|null>(null),[checks,setChecks]=useState<ThesisCheck[]>([]);
  const [projectId,setProjectId]=useState(initialProject),[metric,setMetric]=useState<ThesisMetric>("transfer-counter"),[claim,setClaim]=useState(""),[threshold,setThreshold]=useState(10),[hours,setHours]=useState(8),[count,setCount]=useState(16),[interval,setInterval]=useState(30);
  const [busy,setBusy]=useState(""),[error,setError]=useState(""),[compose,setCompose]=useState(true);
  const target=catalog.find(p=>p.id===projectId);
  useEffect(()=>{void Promise.all([request("/api/theses"),request("/api/radar")]).then(([a,b])=>{setTheses(a.theses);setCatalog([...projects,...b.projects]);}).catch(()=>setError("Workspace or radar unavailable. Existing data is not replaced."));},[]);
  useEffect(()=>{if(target)setMetric(target.repo?"repository-head":target.researchKind==="contract"?"transaction-counter":"transfer-counter");},[target?.id,target?.repo,target?.researchKind]);
  async function select(t:Thesis){setBusy("Loading thesis");setError("");try{const data=await request(`/api/theses/${t.id}`);setSelected(data.thesis);setChecks(data.checks);setCompose(false);}catch(e){setError(e instanceof Error?e.message:"Thesis unavailable.");}finally{setBusy("");}}
  async function create(){setBusy("Recording baseline");setError("");try{const data=await request("/api/theses",{projectId,claim,metric,threshold,hours,checks:count,intervalMinutes:interval});setSelected(data.thesis);setChecks([]);setCompose(false);setTheses((await request("/api/theses")).theses);}catch(e){setError(e instanceof Error?e.message:"Could not create thesis.");}finally{setBusy("");}}
  async function act(action:"check"|"cancel"){if(!selected)return;setBusy(action==="check"?"Checking evidence":"Cancelling");setError("");try{const data=await request(`/api/theses/${selected.id}`,{action});setSelected(data.thesis);setChecks(data.checks);setTheses((await request("/api/theses")).theses);}catch(e){setError(e instanceof Error?e.message:"Thesis action failed.");}finally{setBusy("");}}
  return <div className="workbench"><header className="work-header"><Link className="work-brand" href="/"><Compass size={25}/>ARC MAP</Link><nav aria-label="Main navigation"><Link href="/">Discover</Link><Link href="/hunters">Hunters</Link><Link className="active" href="/theses">Theses</Link><Link href="/map">Map</Link><Link href="/agents">Agents</Link></nav></header>
    <main className="work-main"><div className="work-title"><div><span className="work-kicker">THE THESIS DESK / PRIVATE WORKSPACE</span><h1>A claim. A clock. The evidence.</h1></div><button className="work-refresh work-text-button" onClick={()=>setCompose(true)}><Plus size={16}/>New thesis</button></div><p className="thesis-intro">Put a view on the record, then track what changes. These are observable research criteria—not bets on prices or guaranteed project success.</p>
      {error&&<div className="work-error" role="alert">{error}</div>}
      <div className="thesis-layout"><aside className="thesis-list"><div className="list-caption"><span>YOUR THESES</span><span>{theses.length}</span></div>{!theses.length&&<p className="work-empty">Start with a project you want to watch tomorrow. The baseline comes from its live source.</p>}{theses.map(t=><button key={t.id} className={`thesis-row ${selected?.id===t.id&&!compose?"selected":""}`} onClick={()=>void select(t)} disabled={Boolean(busy)}><small>{t.projectName}</small><strong>{t.claim}</strong><span>{t.status.replaceAll("-"," ")} · until {date(t.deadline)}</span></button>)}</aside>
      <section className="thesis-detail">{compose?<form className="thesis-form" onSubmit={e=>{e.preventDefault();void create();}}><span className="work-kicker">WRITE THE RULE BEFORE THE RESULT</span><h2>What do you expect to change?</h2><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}>{catalog.filter(p=>p.contract||p.repo).map(p=><option value={p.id} key={p.id}>{p.name}{p.contract?` · ${p.contract.slice(0,8)}…`:""}</option>)}</select></label><label>Your thesis<textarea value={claim} onChange={e=>setClaim(e.target.value)} minLength={10} maxLength={400} required placeholder="I expect this project’s onchain activity to continue beyond its initial distribution."/></label><label>Observable criterion<select value={metric} onChange={e=>setMetric(e.target.value as ThesisMetric)}>{(target?.repo?["repository-head"]:target?.researchKind==="contract"?["transaction-counter"]:["transfer-counter","holder-counter"]).map(m=><option key={m} value={m}>{labels[m as ThesisMetric]}</option>)}</select></label>
      <div className="thesis-form-grid">{metric!=="repository-head"&&<label>Increase by at least<input type="number" min={1} max={1000000} value={threshold} onChange={e=>setThreshold(Number(e.target.value))} required/></label>}<label>Horizon (hours)<input type="number" min={1} max={168} value={hours} onChange={e=>setHours(Number(e.target.value))} required/></label><label>Check every (minutes)<input type="number" min={15} max={1440} value={interval} onChange={e=>setInterval(Number(e.target.value))} required/></label><label>Maximum checks<input type="number" min={1} max={24} value={count} onChange={e=>setCount(Number(e.target.value))} required/></label></div>
      <p className="setup-note">Creating this thesis opts into the finite read-only schedule above. No funds move. The claim, criterion, baseline and horizon are locked; cancel at any time. A running source worker is required.</p><button className="work-primary-button" disabled={Boolean(busy)||!target}>{busy||"Record thesis and start tracking"}<ArrowRight size={16}/></button></form>:selected?<>
        <div className="report-heading"><div><span className="work-kicker">{selected.projectName}</span><h2>{selected.claim}</h2></div><span className={`status-label ${selected.status}`}>{selected.status.replaceAll("-"," ")}</span></div><p className="thesis-rule">{labels[selected.metric]}{selected.metric!=="repository-head"?` by at least ${selected.threshold.toLocaleString()}`:""}, observed by {date(selected.deadline)}.</p>
        <div className="report-facts"><div><strong>{typeof selected.baseline.value==="number"?selected.baseline.value.toLocaleString():selected.baseline.value.slice(0,10)}</strong><span>pinned baseline</span></div><div><strong>{checks.length}</strong><span>completed checks</span></div><div><strong>{selected.remainingChecks}</strong><span>checks remaining</span></div><div><strong>{selected.intervalMinutes}m</strong><span>chosen interval</span></div></div>
        <Trajectory thesis={selected} checks={checks}/>
        <div className="thesis-actions"><button className="work-primary-button" disabled={Boolean(busy)||selected.status!=="tracking"} onClick={()=>void act("check")}><RefreshCw size={15}/>{busy||"Check evidence now"}</button><button className="work-refresh" disabled={Boolean(busy)||selected.status!=="tracking"} onClick={()=>void act("cancel")}><Pause size={15}/>Cancel checks</button><Link className="evidence-link" href={`/projects/${encodeURIComponent(selected.projectId)}`}><Crosshair size={15}/>Inspect project</Link></div>
        <p className="report-time">{selected.nextCheckAt?`Next scheduled check ${date(selected.nextCheckAt)}; requires a running worker.`:"No further checks are scheduled."} Manual checks also consume the stated check count.</p>
        <h3>Evidence trail</h3><a className="evidence-link" href={selected.baseline.sourceUrl} target="_blank" rel="noreferrer">Baseline observed {date(selected.baseline.observedAt)}<ArrowUpRight size={13}/></a>
        {checks.map(c=><article className="thesis-check" key={c.id}><span className="work-kicker">{date(c.checkedAt)} · {c.error?"SOURCE UNAVAILABLE":c.met?"CRITERION OBSERVED":"CHECKED"}</span><p>{c.observation}</p>{c.error&&<p className="setup-note">{c.error}</p>}{c.sample&&<a className="evidence-link" href={c.sample.sourceUrl} target="_blank" rel="noreferrer">Inspect source <ArrowUpRight size={13}/></a>}</article>)}
        <p className="setup-note">“Observed” means the chosen source criterion was met. “Not observed” means no check established it before the deadline—not proof that nothing happened. “Inconclusive” can mean source failure or exhausted checks. None of these states measures investment quality.</p><details><summary>Locked thesis commitment</summary><code className="report-hash">{selected.commitment}</code><p className="report-time">Local SHA-256 content commitment, not an onchain receipt.</p></details>
      </>:<p className="work-empty">Select a thesis to inspect its evidence.</p>}</section></div><footer className="work-footer"><span>Private browser workspace · not shared across accounts</span><span>Read-only research · no trades or tokens issued</span></footer>
    </main></div>;
}
